version: 1.0.{build}

image: Visual Studio 2019

configuration: Release

platform: Any CPU

before_build:
  - ps: nuget restore LibreHardwareMonitor.sln
  
build:
  project: LibreHardwareMonitor.sln
  verbosity: minimal

artifacts:
  - path: 'Bin\Release\'
