name: build zip

on:
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # 5.2.0
        with:
          dotnet-version: '10.0.x'

      - name: Restore application packages
        run: dotnet restore LibreHardwareMonitor.Windows.Forms\LibreHardwareMonitor.Windows.Forms.csproj

      - name: Build application
        run: dotnet build LibreHardwareMonitor.Windows.Forms\LibreHardwareMonitor.Windows.Forms.csproj -c Release --no-restore -p:Platform=x64

      - name: Create zip archives
        shell: pwsh
        run: |
          Compress-Archive -Path "bin\Release\net472\*" -DestinationPath "LibreHardwareMonitor-win-net472-x64.zip" -CompressionLevel Optimal
          Compress-Archive -Path "bin\Release\net10.0-windows\*" -DestinationPath "LibreHardwareMonitor-win-net10-x64.zip" -CompressionLevel Optimal

      - name: Upload zip archives
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: LibreHardwareMonitor-zips
          path: |
            LibreHardwareMonitor-win-net472-x64.zip
            LibreHardwareMonitor-win-net10-x64.zip
          if-no-files-found: error
